AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for AWS Expense Reimbursement System

Resources:

  ExpenseReceiptBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "expense-receipts-${AWS::AccountId}"
  
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess


SubmitExpenseFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: SubmitExpenseFunction
      Handler: index.lambda_handler
      Runtime: python3.10
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {
                  'statusCode': 200,
                  'body': 'Expense submitted successfully!'
              }
      Timeout: 5

      
ApproveExpenseFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ApproveExpenseFunction
      Handler: index.lambda_handler
      Runtime: python3.10
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import json

          def lambda_handler(event, context):
              body = json.loads(event.get('body', '{}'))
              expense_id = body.get('expense_id')
              approved = body.get('approved')  # True or False
              manager_id = body.get('manager_id')

              if not expense_id or approved is None:
                  return {
                      'statusCode': 400,
                      'body': json.dumps({'message': 'Invalid input'})
                  }

              status = 'approved' if approved else 'rejected'

              return {
                  'statusCode': 200,
                  'body': json.dumps({
                      'message': f'Expense {expense_id} has been {status}.',
                      'manager_id': manager_id
                  })
              }
      Timeout: 5
